/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientView.java
 *
 * Created on Feb 24, 2012, 1:39:04 PM
 */
package Views;

import Classes.SaveSettings;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileFilter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author afannin1
 */
public class ClientView extends javax.swing.JPanel {

    private String apiKey;
    private String projectKey;
    private String startLine; 
    private File file;
    private int days;
    private int hours;
    private int minutes;
    private int timeOut;
    private Boolean flag = true;
    DefaultTableModel tableModel;
    /** Creates new form ClientView */
    public ClientView() {
        initComponents();
        createTableModel();
        populateComboBoxes();
        getPreferences();
    }
    
    public String getApiKey() {
        return apiKey;
    }
    
    public void setApiKey(String key) {
        this.apiKey = key;
    }
    
    public String getProjectKey() {
        return projectKey;
    }
    
    public void setProjectKey(String key) {
        this.projectKey = key;
    }
    
    public String getTemplateId() {
        return templateComboBox.getSelectedItem().toString();
    }
    
    public String getSite() {
        return siteComboBox.getSelectedItem().toString();
    }
    
    public String getStartLine() {
        return startLine;
    }
    
    public void setStartLine(String line) {
        this.startLine = line;
    }
    
    public File getFile() {
        return file;
    }
    
    public void setFile(File file) {
        this.file = file;
    }
    
    public int getDays() {
        return Integer.valueOf(daysComboBox.getSelectedItem().toString());
    }
    
    public void setDays(int days) {
        daysComboBox.setSelectedItem(days);
    }
    
    public int getHours() {
        return Integer.valueOf(hoursComboBox.getSelectedItem().toString());
    }
    
    public void setHours(int hours) {
        hoursComboBox.setSelectedItem(hours);
    }    
    
    public int getMinutes() {
        return Integer.valueOf(minutesComboBox.getSelectedItem().toString());
    }
    
    public void setMinutes(int minutes) {
        minutesComboBox.setSelectedItem(minutes);
    }

    public int getTimeOut() {
        return Integer.valueOf(timeoutComboBox.getSelectedItem().toString());
    }
    
    public void setTimeOut(int timeOut) {
        timeoutComboBox.setSelectedItem(timeOut);
    }
    
    public void setSitesComboBox(String str) {
        siteComboBox.addItem(str);
    }
    
    public void setTemplateComboBox(String str) {
        templateComboBox.addItem(str);
    }
    
    public void clearSiteComboBox() {
        siteComboBox.removeAllItems();
    }
    
    public void clearTemplateComboBox() {
        templateComboBox.removeAllItems();
    }
    
    public Boolean getFlag() {
        return flag;
    }
    
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultsPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        daysComboBox = new javax.swing.JComboBox();
        hoursComboBox = new javax.swing.JComboBox();
        minutesComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timeoutComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        apiTextField = new javax.swing.JTextField();
        projectTextField = new javax.swing.JTextField();
        saveKeyButton = new javax.swing.JButton();
        resetKeyButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        siteComboBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        templateComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();

        resultsPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                resultsPaneStateChanged(evt);
            }
        });

        jLabel1.setText("Push Interval:");

        daysComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        hoursComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        minutesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Days");

        jLabel3.setText("Hours");

        jLabel4.setText("Minutes");

        jLabel5.setText("Timeout (mins):");

        timeoutComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(minutesComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hoursComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(daysComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timeoutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(daysComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(timeoutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minutesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        resultsPane.addTab("Service Control", jPanel1);

        jLabel7.setText("API Key:");

        jLabel8.setText("Project Key:");

        apiTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                apiTextFieldFocusLost(evt);
            }
        });

        projectTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                projectTextFieldFocusLost(evt);
            }
        });

        saveKeyButton.setText("Validate Keys");

        resetKeyButton.setText("Reset Keys");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(saveKeyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetKeyButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                            .addComponent(projectTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(apiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(projectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetKeyButton)
                    .addComponent(saveKeyButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        resultsPane.addTab("User Settings", jPanel2);

        jLabel10.setText("Site:");

        jLabel11.setText("Data Template Id:");

        jLabel9.setText("File to Push:");

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(templateComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(siteComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 186, Short.MAX_VALUE))
                    .addComponent(pathTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(siteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(templateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        resultsPane.addTab("Upload Parameters", jPanel3);

        eventTable.setModel(tableModel = new javax.swing.table.DefaultTableModel());
        jScrollPane1.setViewportView(eventTable);

        jLabel6.setText("Event Log:");

        startButton.setText("Start Service");

        stopButton.setText("Stop Service");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultsPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopButton)
                    .addComponent(startButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        loadFile();
    }//GEN-LAST:event_browseButtonActionPerformed

    private void apiTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apiTextFieldFocusLost
        apiKey = apiTextField.getText();
    }//GEN-LAST:event_apiTextFieldFocusLost

    private void projectTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_projectTextFieldFocusLost
        projectKey = projectTextField.getText();
    }//GEN-LAST:event_projectTextFieldFocusLost

    private void resultsPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_resultsPaneStateChanged
        if (resultsPane.getSelectedIndex() == 2) {
          if (siteComboBox.getItemCount() < 1) {
            int x;
            x = JOptionPane.showConfirmDialog(null,"It appears that you have not validated your API and Project Keys.\nTo use this form you must first validate your keys.\nValidate keys now?", "Keys Not Validated", JOptionPane.YES_NO_OPTION);
            if (x == JOptionPane.YES_OPTION) {
                saveKeyButton.doClick();
            }
          }
       }
    }//GEN-LAST:event_resultsPaneStateChanged

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apiTextField;
    private javax.swing.JButton browseButton;
    private javax.swing.JComboBox daysComboBox;
    private javax.swing.JTable eventTable;
    private javax.swing.JComboBox hoursComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox minutesComboBox;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JTextField projectTextField;
    private javax.swing.JButton resetKeyButton;
    private javax.swing.JTabbedPane resultsPane;
    private javax.swing.JButton saveKeyButton;
    private javax.swing.JComboBox siteComboBox;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JComboBox templateComboBox;
    private javax.swing.JComboBox timeoutComboBox;
    // End of variables declaration//GEN-END:variables

    public void loadFile() {
        getFilePath();
        pathTextField.setText(file.toString());
    }    
    
        private void getFilePath() {
        JFileChooser chooser = new JFileChooser();
        FileFilter filter = null; 
        chooser.setDialogTitle("Open File");
        int returnVal = chooser.showOpenDialog(this); 

        try {
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            setFile(chooser.getSelectedFile());
            this.addEventRecord(this.getTimeStamp(), "File " + chooser.getSelectedFile() + " has been chosen for upload", "Success");
        }   
        }
        catch(NullPointerException ex) {
            //Do nothing.  This is thrown on a Cancel operation and Close
        }
    }
     
    public void setActionListeners(ActionListener al) {
        startButton.setActionCommand("start");
        startButton.addActionListener(al);
        stopButton.setActionCommand("stop");
        stopButton.addActionListener(al);
        saveKeyButton.setActionCommand("saveKeys");
        saveKeyButton.addActionListener(al);
        resetKeyButton.setActionCommand("resetKeys");
        resetKeyButton.addActionListener(al);
        siteComboBox.setActionCommand("siteChanged");
        siteComboBox.addActionListener(al);
    }                                                                        

    private void populateComboBoxes() {
        daysComboBox.removeAllItems();
        hoursComboBox.removeAllItems();
        minutesComboBox.removeAllItems();
        timeoutComboBox.removeAllItems();
        
        for(int i = 0; i <= 31; i++) {
            daysComboBox.addItem(i);
        }
        
        for (int i = 0; i < 24; i ++) {
            hoursComboBox.addItem(i);
        }
        
        for (int i = 0; i < 60; i++) {
            minutesComboBox.addItem(i);
        }
        
        for (int i = 0; i <= 60; i += 5 ) {
            timeoutComboBox.addItem(i);
        }
    }

    public void setTextFields() {
        pathTextField.setText("");
        apiTextField.setText("");
        projectTextField.setText("");
        //templateTextField.setText("");
        //lineTextField.setText("");
    }

    public void addEventRecord(String timeStamp, String message, String status) {
        String[] row = new String[3];
        row[0] = timeStamp;
        row[1] = message;
        row[2] = status;
        tableModel.addRow(row);
    }
    
    private void createTableModel() {
        tableModel.addColumn("Time Stamp");
        tableModel.addColumn("Message");
        tableModel.addColumn("Status");
    }

    private void getPreferences() {
       SaveSettings settings = new SaveSettings();
        apiKey = settings.getApiKey();
        apiTextField.setText(apiKey);
        setProjectKey(settings.getProjectKey());
        projectTextField.setText(projectKey);
        setDays(settings.getDays());
        setHours(settings.getHours());
       setMinutes(settings.getMinutes());
        setTimeOut(settings.getTimeOut());
   }

    private void isSaved() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    
    //Adding this in the view is redundant.  This could be refactored into a date class if it needs to be used often
    private String getTimeStamp() {
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
        Date timeStamp = new Date();
        return dateFormat.format(timeStamp);
    }
}
