/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainView.java
 *
 * Created on Jan 17, 2012, 9:28:28 AM
 */
package Views;

import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileFilter;
import javax.swing.JFileChooser;

/**
 *
 * @author afannin1
 */
public class MainView extends javax.swing.JPanel {
    File path;

    private String apiKey;
    private String projectKey;
    private String templateId;
    private String startLine; 
    private File file;
    /** Creates new form MainView */
    public MainView() {
        initComponents();
    }
    
    public String getApiKey() {
        return apiKey;
    }
    
    public void setApiKey(String key) {
        this.apiKey = key;
    }
    
    public String getProjectKey() {
        return projectKey;
    }
    
    public void setProjectKey(String key) {
        this.projectKey = key;
    }
    
    public String getTemplateId() {
        return templateId;
    }
    
    public void setTemplateId(String id) {
        this.templateId = id;
    }
    
    public String getStartLine() {
        return startLine;
    }
    
    public void setStartLine(String line) {
        this.startLine = line;
    }
    
    public File getFile() {
        return file;
    }
    
    public void setFile(File file) {
        this.file = file;
    }

    public void loadFile() {
        getFilePath();
        pathTextField.setText(file.toString());
    }    
    
    private void getFilePath() {
        JFileChooser chooser = new JFileChooser();
        FileFilter filter = null; 
        chooser.setDialogTitle("Open File");
        int returnVal = chooser.showOpenDialog(this); 

        try {
        if (returnVal == JFileChooser.APPROVE_OPTION)
            setFile(chooser.getSelectedFile());
        }
        catch(NullPointerException ex) {
            //Do nothing.  This is thrown on a Cancel operation and Close
        }
    }
     
    public void setActionListeners(ActionListener al) {
        uploadButton.setActionCommand("upload");
        uploadButton.addActionListener(al);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        uploadButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lineLabel = new javax.swing.JLabel();
        lineTextField = new javax.swing.JTextField();
        apiLabel = new javax.swing.JLabel();
        projectLabel = new javax.swing.JLabel();
        templateLabel = new javax.swing.JLabel();
        templateTextField = new javax.swing.JTextField();
        projectTextField = new javax.swing.JTextField();
        apiTextField = new javax.swing.JTextField();
        fileLabel = new javax.swing.JLabel();

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        uploadButton.setText("Upload");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        lineLabel.setText("Start Line:");

        lineTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lineTextFieldFocusLost(evt);
            }
        });

        apiLabel.setText("API Key:");

        projectLabel.setText("Project Key:");

        templateLabel.setText("Template ID:");

        templateTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                templateTextFieldFocusLost(evt);
            }
        });

        projectTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                projectTextFieldFocusLost(evt);
            }
        });

        apiTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                apiTextFieldFocusLost(evt);
            }
        });

        fileLabel.setText("File Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(templateLabel)
                            .addComponent(apiLabel)
                            .addComponent(projectLabel)
                            .addComponent(lineLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(templateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(lineTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(apiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileLabel)
                                .addGap(18, 18, 18)
                                .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(browseButton))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(340, Short.MAX_VALUE)
                        .addComponent(uploadButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileLabel)
                    .addComponent(browseButton))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apiLabel)
                    .addComponent(apiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectLabel)
                    .addComponent(projectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(templateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(templateLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lineLabel)
                    .addComponent(lineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(uploadButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        loadFile();
    }//GEN-LAST:event_browseButtonActionPerformed

    private void lineTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lineTextFieldFocusLost
        startLine = lineTextField.getText();
    }//GEN-LAST:event_lineTextFieldFocusLost

    private void templateTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_templateTextFieldFocusLost
        templateId = templateTextField.getText();
    }//GEN-LAST:event_templateTextFieldFocusLost

    private void projectTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_projectTextFieldFocusLost
        projectKey = projectTextField.getText();
    }//GEN-LAST:event_projectTextFieldFocusLost

    private void apiTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apiTextFieldFocusLost
        apiKey = apiTextField.getText();
    }//GEN-LAST:event_apiTextFieldFocusLost

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apiLabel;
    private javax.swing.JTextField apiTextField;
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lineLabel;
    private javax.swing.JTextField lineTextField;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JTextField projectTextField;
    private javax.swing.JLabel templateLabel;
    private javax.swing.JTextField templateTextField;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables

    public void setTextFields() {
        pathTextField.setText("");
        apiTextField.setText("");
        projectTextField.setText("");
        templateTextField.setText("");
        lineTextField.setText("");
    }

}
